### ISSUE TITLE
license terms missing

### ISSUE THREAD

**Issue by keisentraut** [JaredWright/WFPStarterKit#3]
Thanks for this starting point, it helped a lot to understand WFP.

Can you please [add a license](https://help.github.com/en/articles/adding-a-license-to-a-repository) to this code? I'll rewrite it from scratch for a (commercial) prototype anyway, so it doesn't matter a lot, but I cannot credit you without it. I would prefer MIT, but it's up to you. Thanks!

**Comment by JaredWright** [comment]
Thanks @keisentraut, its great to hear that this project is still useful even after 4 years!

Excellent suggestion, an MIT license was added to the project just now (thats my license preference as well).

**Comment by keisentraut** [comment]
FYI: I ended up using the excellent [WinDivert](https://reqrypt.org/windivert.html) project. This saved me from all the hassle associated with writing a custom kernel driver and user mode packet parsing code myself.
